import Config from 'react-native-config';

export const ENV = {
  API_URL: Config.API_URL || '',
  SHARETRIBE_SDK_CLIENT_ID: Config.SHARETRIBE_SDK_CLIENT_ID || '',
  SHARETRIBE_SDK_CLIENT_SECRET: Config.SHARETRIBE_SDK_CLIENT_SECRET || '',
  SHARETRIBE_SDK_TRANSIT_VERBOSE: Config.SHARETRIBE_SDK_TRANSIT_VERBOSE || '',
  SHARETRIBE_USING_SSL: Config.SHARETRIBE_USING_SSL || '',
  SDK_ASSET_CDN_BASE_URL: Config.SDK_ASSET_CDN_BASE_URL || '',
  MARKETPLACE_NAME: Config.MARKETPLACE_NAME || '',
  MARKETPLACE_ROOT_URL: Config.MARKETPLACE_ROOT_URL || '',
  STRIPE_PUBLISHABLE_KEY: Config.STRIPE_PUBLISHABLE_KEY || '',
  MAPBOX_ACCESS_TOKEN: Config.MAPBOX_ACCESS_TOKEN || '',
  APP_ENV: Config.APP_ENV || 'development',
  SDK_BASE_URL: Config.SDK_BASE_URL || '',
  REACT_NATIVE_SDK_BASE_URL: Config.REACT_NATIVE_SDK_BASE_URL || '',
  SENTRY_DSN: Config.SENTRY_DSN || '',
};
